/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
#include <stdint.h>

/* RCC AHB2 peripheral clock enable register */
#define RCC_AHB2ENR   (*((volatile uint32_t*)0x4002104C))

/* GPIOA registers */
#define GPIOA_MODER   (*((volatile uint32_t*)0x48000000))
#define GPIOA_ODR     (*((volatile uint32_t*)0x48000014))

/* Simple delay */
void delay(volatile uint32_t count)
{
    while(count--);
}

int main(void)
{
    /* Step 1: Enable clock for GPIOA - bit 0 of RCC_AHB2ENR */
    RCC_AHB2ENR |= (1U << 0);

    /* Step 2: Set PA5 as output - bits 11:10 = 01 in MODER */
    GPIOA_MODER &= ~(3U << 10);  /* Clear bits 11:10 */
    GPIOA_MODER |=  (1U << 10);  /* Set to output mode */

    /* Step 3: Blink forever */
    while(1)
    {
        GPIOA_ODR |=  (1U << 5);  /* LED on  */
        delay(500000);
        GPIOA_ODR &= ~(1U << 5);  /* LED off */
        delay(500000);
    }
}
